//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnivarsityManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public int ID { get; set; }
        public string u_name { get; set; }
        public string u_password { get; set; }
        public string u_type { get; set; }
    
        public virtual student student { get; set; }
        public virtual TeacherTable TeacherTable { get; set; }
    }
}
